[package]
name = "crowdfunding-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.crowdfunding]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.4"
default-features = false
